### ISSUE TITLE
Brainstorm better names for DBS

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/uploader_backend#85]
As we gear up to launch the DBS, it's worth considering if we can come up with a better and more consumer-friendly name for this project. 

**Issue:** 
Decentralized backend storage is too long and sounds like something only for developers. 

Using the DBS acronym is even worse as it doesn't convey any information and will be hard for people to Google.

**Comment by jamiehewitt15** [comment]
A few initial suggestions to get the discussion going:

OceanStore
WaveVault
StorageHub
StorageSea
DecentraStorage
DataStore
DataDome
DataHub
UniStore

**Comment by paulo-ocean** [comment]
OceanVault
OceaChest
OceanLocker
OceanCache
?

**Comment by andreaarmanni** [comment]
Great initiative. I would perhaps avoid using words like Storage and Data, since we're not really storing using Ocean and we can upload any type of files really. 

Some ideas:

FileSystem
OceanConnector
OceanUploader
FileUploader

**Comment by sheriff4** [comment]
Thanks Jamie! 
"StorageHub" strikes a chord. 
Otherwise how about:
- ElasticStorage
- OceanScaler
- MultiFiler

**Comment by nickscavuzzo33** [comment]
Nice work on this @jamiehewitt15 
+1 on StorageHub
- other votes:
TreasureChest 
OceanVault 
DeepSeaDataVault
OceanFloor 
MarinerMemory

**Comment by jamiehewitt15** [comment]
@andreaarmanni Yeah, I think you make a good point about us not actually offering storage directly and it's really more of an uploader, your suggestions of OceanUploader and FileUploader convey that nicely. Another option could be Ocean UploadHub.

**Comment by sheriff4** [comment]
I disagree on the "upload" positioning - we should avoid giving the impression that Ocean is collecting data by asking individuals to upload it.

**Comment by andreaarmanni** [comment]
> I disagree on the "upload" positioning - we should avoid giving the impression that Ocean is collecting data by asking individuals to upload it.

I see your concerns. It gets difficult now, maybe **FileManager** but I don't know to what extent users can manage files from there, aside from just uploading them. Alternatively something related to "publishing".

**Comment by mihaisc** [comment]
Ocean StorageHub?

**Comment by trentmc** [comment]
When we name something, we need specs. This comment discusses specs, and summarizes actual specs at the end.

"DBS" is a problem because it makes it sound like it's doing storage. 
- Ie competitive with Arweave and Filecoin. 
- Yet of course it isn't doing storage, and is complementary to Arweave and Filecoin. 
- Therefore it really does need a better name.

It also doesn't need a fancy brand name. 
- It's just another component in the Ocean system that does a specific thing, with relatively mundane goals. (I'm not saying it was easy to do, though:) 
- A fancy brand name makes it harder for outsiders to track Ocean products.
- Datapoint: in v1 and v2, Provider and ocean.py and ocean.js had fancier names, and it caused huge confusion because it was hard to track what each name did.

It doesn't explicitly need "Ocean" in it either. That will go next to it when appropriate. Like "Ocean Provider."

It doesn't need"decentralized" in it either. That's a lot of characters for a characteristic that is in every Ocean component.

The name should be sufficient The short that we don't need an acronym to refer to it. (Am acronym adds confusion because it's another layer of indirection.)

It shouldn't have "hub", because hub implies a platform, a specific type of platform that people come to for all things (eg all things storage). Like github for all things git. It's not trying to be that, and shouldn't be.

The name should be short, and descriptive.

What's the (mundane) thing it's doing? In software design patterns terms, it's an **"adapter"**.
- it's just a pass through from one system to another. No more no less. 
- Like an EU/USA power adapter.
- It's an adapter from actual decentralized file storage, to higher level Ocean components that use them 

Specs: one liner:
- have a short, clear name that makes it obvious what it does 

Specs: details 
- be descriptive of what it actually does. (Adapter for storage)
- don't imply functionality that it doesn't do. (Eg don't imply "does storage" or "is a hub")
- be short 
  - therefore: avoid words that add little in description ("decentralized", "Ocean")
  - if it needs an acronym, its too long 
- be mundane, not fancy 
- have a clear name that makes it obvious what it does 

Specs: one liner:
- have a short, clear name that makes it obvious what it does

**Comment by trentmc** [comment]
A bit more on naming specs:

Actually, besides "adapter" there is a second component too: a gui widget (built into a dapp) to help uploading. 

- fyi there are many of these in the filecoin and arweave ecosystems
- some are very easy to use, having been refined over years by many people
- Therefore we shouldn't assume that the Ocean version is the best. As far as I can tell, other ones are much lower friction to use 
- so trying to compete with them will be an uphill battle, that we have not committed the resources to do 
- rather, it's best to think of this gui widget as something useful within the context of the Ocean set of tools, not as a standalone tool

**Comment by trentmc** [comment]
Given the specs above, here are some possible names. "Ocean" can go in front of them when appropriate.

For adapter part:
- Storage Adapter 
- Upload Adapter
- Upload Backend  

For frontend gui part:
- Uploader 
- Upload Widget
- Upload Gui
- Upload Dapp
- Uploader 

For both parts at once:
- "Uploader"
- "Uploader". With "Uploader Backend" and "Uploader Gui" when we want to drill in

I'd be fine with any of the above. And to me the best option is the latter one. That is:
- "(Ocean) Uploader". With "Uploader Backend" and "Uploader Gui" when we want to drill in

**Comment by AnaLoznianu** [comment]
One thing to keep in mind once we decide on a name:
- [ ] update repos to reflect the newly selected name
